### ISSUE TITLE
Add a readme.

### ISSUE THREAD

**Issue by nk521** [aa-deet-eeya/3js#1]
Explain what this project is and how can anyone run it.

**Comment by aa-deet-eeya** [comment]
This 'project' is still in the development phase with no clear end goal at this point of time, it's supposed to be a sort of experimentation with [Three.js](https://threejs.org/) and probably a 3D object rendering scene. 

Will add more info as I decide what to do with this next. Right now it's boilerplate code with no scene to show.
 However, 
`npm install` and `npm run server`
will run the code

**Comment by NamanShergill** [comment]
I agree, a readme is very important.
